# Generated by Django 2.2 on 2019-06-19 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='endday',
            field=models.DateField(default=datetime.date(2000, 12, 31)),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='friday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='monday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='saturday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='startday',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='sunday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='thursday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='tuesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='wednesday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studymeeting',
            name='info',
            field=models.CharField(default='', max_length=20),
        ),
    ]
