# Generated by Django 2.2 on 2019-05-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymeeting',
            name='info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
