# Generated by Django 2.2 on 2019-05-11 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0003_studygroupnotice_studymeetingnotice'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymeeting',
            name='members',
            field=models.ManyToManyField(related_name='study_meetings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studymeeting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_meetings', to='study.StudyGroup'),
        ),
        migrations.CreateModel(
            name='StudyGroupPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField(default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='study.StudyGroup')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
