# Generated by Django 2.2 on 2019-04-28 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0003_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studygroup',
            name='users',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='study_groups_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='study_groups_owned', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
