# Generated by Django 2.2 on 2019-05-26 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0006_auto_20190518_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingFine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='StudyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='studytest',
            name='group',
        ),
        migrations.RemoveField(
            model_name='studytest',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='studytest',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='studyusersetting',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='studymeeting',
            options={'ordering': ('created',)},
        ),
        migrations.RenameField(
            model_name='fine',
            old_name='amount',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='fine',
            name='policy',
        ),
        migrations.AddField(
            model_name='policy',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='study.StudyUser'),
        ),
        migrations.AlterField(
            model_name='fine',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='study.StudyUser'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='members',
            field=models.ManyToManyField(related_name='study_groups_join', to='study.StudyUser'),
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_groups_own', to='study.StudyUser'),
        ),
        migrations.AlterField(
            model_name='studygroupnotice',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_group_notices', to='study.StudyGroup'),
        ),
        migrations.AlterField(
            model_name='studygroupnotice',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_group_notices', to='study.StudyUser'),
        ),
        migrations.AlterField(
            model_name='studymeeting',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_meetings', to='study.StudyGroup'),
        ),
        migrations.AlterField(
            model_name='studymeeting',
            name='members',
            field=models.ManyToManyField(related_name='study_meetings', to='study.StudyUser'),
        ),
        migrations.AlterField(
            model_name='studymeetingnotice',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_meeting_notices', to='study.StudyMeeting'),
        ),
        migrations.AlterField(
            model_name='studymeetingnotice',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_meeting_notices', to='study.StudyUser'),
        ),
        migrations.DeleteModel(
            name='StudyFile',
        ),
        migrations.DeleteModel(
            name='StudyTest',
        ),
        migrations.DeleteModel(
            name='StudyUserSetting',
        ),
        migrations.AddField(
            model_name='meetingfine',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_fines', to='study.StudyMeeting'),
        ),
        migrations.AddField(
            model_name='meetingfine',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_fines', to='study.Policy'),
        ),
        migrations.AddField(
            model_name='fine',
            name='meeting_fine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='study.MeetingFine'),
        ),
    ]
