# Generated by Django 2.2 on 2019-06-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20190526_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
