# Generated by Django 2.2 on 2019-06-17 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_studygroup_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studymeeting',
            name='members',
        ),
    ]
