# Generated by Django 2.2 on 2019-06-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_remove_studymeeting_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='count',
        ),
        migrations.RemoveField(
            model_name='meetingfine',
            name='name',
        ),
        migrations.AddField(
            model_name='policy',
            name='info',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='policy',
            name='amount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
