# Generated by Django 2.2 on 2019-06-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_auto_20190617_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='studygroup',
            name='attendance_amount',
            field=models.IntegerField(default=0),
        ),
    ]
